services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: credits_total_kz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://app:apppass@db:5432/appdb
    depends_on:
      - db
    command: ["python", "-V"]

volumes:
  pgdata:
