services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: credits_total_kz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.9.0
    depends_on:
      - db
    env_file:
      - .env
    environment:
      MLFLOW_ALLOWLISTED_HOSTS: "mlflow,localhost,mlflow:5000,127.0.0.1"
      MLFLOW_HOST: "0.0.0.0"
      
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    command: >
      bash -lc "
      pip install -q psycopg2-binary &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri $DATABASE_URL/mlflow
      --default-artifact-root $MLFLOW_DEFAULT_ARTIFACT_ROOT
      --allowed-hosts localhost,127.0.0.1,mlflow,localhost:5000,mlflow:5000
      "

  app:
    build:
      context: .
    depends_on:
      - db
      - mlflow
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["bash", "-lc", "./run_pipeline.sh"]

    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4:8
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata: {}
  mlflow_artifacts: {}
  pgadmin_data: {}
